name: brsm_id
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.4.4
  firebase_auth: 5.7.0
  font_awesome_flutter: ^10.10.0


  # Для HTTP-запросов
  http: ^1.2.0

  # Для парсинга HTML
  html: ^0.15.4

  # Для открытия ссылок в браузере
  url_launcher: ^6.2.0
  mobile_scanner: ^7.1.3
  image_picker: ^1.2.0
  firebase_storage: ^12.4.10
  cloudinary: ^1.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
